### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by pengowen123** [pengowen123/cmaes#4]
Building currently does not work on Windows due to issues with compiling netlib, but using Intel's MKL might work instead (see [this comment](https://github.com/pengowen123/cmaes/issues/3#issuecomment-1054749730)).

**Comment by pnevyk** [comment]
How about making `nalgebra_lapack` an optional dependency and use pure `nalgebra` for everything by default? Users could opt in into using `nalgebra_lapack` by enabling one of the lapack backend features. By opting in, the user makes a decision to deal with the platform compatibility issues. But by default, the crate should work just fine everywhere as nalgebra itself is pure Rust.

It seems that the only place where nalgebra_lapack is used is [here](https://github.com/pengowen123/cmaes/blob/db2a831f58a464634829cedb31a6b3cdd0b32ee3/src/matrix.rs#L65). I replaced it with [counterpart](https://docs.rs/nalgebra/latest/nalgebra/linalg/struct.SymmetricEigen.html) from nalgebra. There are two more parameters for `try_new` constructor, but it's just matter of providing some sane values for them. All tests but one passed, but the failure was just about different number of function evaluations, which I guess is due to a difference in the algorithms.

I can send a PR if you agree with this approach.

**Comment by pengowen123** [comment]
That seems like a good solution, feel free to open a PR for it! Just one note about the arguments for `try_new`. Swapping to `SymmetricEigen` from `nalgebra` results in some more test failures for me in `general.rs` that I imagine are due to numerical precision differences between `nalgebra` and `nalgebra_lapack`. However, decreasing the `eps` argument to around `1e-20` seems to fix the tests. The various fixed seed tests will still fail, but that's expected and shouldn't cause any issues.
