### ISSUE TITLE
Can evaluation be parallelized over individuals?

### ISSUE THREAD

**Issue by torshind** [pengowen123/cmaes#6]
Hello,
First of all, congratulations for the work you have done.
In some of my tests the objective function is quite heavy, and I can't help but notice that the solver loop uses just 1 core at once.
I can't find a setting to enable parallelism, is this my fault or is there not? And if so, is it planned?

Kind regards.

**Comment by pengowen123** [comment]
There is currently no option for parallel objective function execution, but it is planned for the next release.

**Comment by pengowen123** [comment]
I've added parallel objective function execution support. If you would like to try it, you can use the `master` branch instead of the crates.io version until the next version is released. Unless you are using a custom type it should be as simple as switching out `CMAES::run` for `CMAES::run_parallel`.
